/** Facts the public pages share, kept in one place so they stay consistent. */
export const GITHUB_URL = "https://github.com/NaderAbsy/sprintwise";
/** A GitHub issue form for ideas and problems. Issues are public, so the form asks for no work data. */
export const FEEDBACK_URL = `${GITHUB_URL}/issues/new?template=feedback.yml`;

/** The public site's tabs, in the header and the footer. */
export const MARKETING_LINKS = [
  { href: "/product", label: "Product" },
  { href: "/guide", label: "Guide" },
  { href: "/demo", label: "Demo" },
  { href: "/about", label: "About" },
];

export type Release = { version: string; date: string; title: string; summary: string; items: string[] };

/** Newest first. Each entry matches a git tag and its GitHub release. */
export const RELEASES: Release[] = [
  {
    version: "v2.15",
    date: "2026-10-10",
    title: "Made for your team",
    summary: "The site now speaks to the people using Sprintwise.",
    items: [
      "Sprintwise describes itself as a free, independent tool instead of a portfolio project.",
      "The demo video ends on what you can do next: try the demo, or sign in with GitHub and use it on your own backlog.",
      "The changelog moved from the top menu to the footer.",
    ],
  },
  {
    version: "v2.14",
    date: "2026-10-09",
    title: "A new demo video",
    summary: "A three-minute walkthrough of today's Sprintwise, and a headline for everyone, however their stories are written.",
    items: [
      "The demo video is re-recorded: Jira import, the AI-draft check, trends, the burn-up, refinement, sharing and the planning helper are all in it now.",
      "The home page headline says what Sprintwise does for you, without suggesting it writes tickets: \"Know your stories are ready before the sprint starts.\"",
    ],
  },
  {
    version: "v2.13",
    date: "2026-10-09",
    title: "Terms, cookies and tidier claims",
    summary: "A terms of use page, a plain list of the cookies Sprintwise sets, and site text that says only what's true.",
    items: [
      "New Terms of use page, linked from the footer and the Privacy page.",
      "The Privacy page lists each cookie and what it's for, the encrypted GitHub sign-in tokens, and the sign-in attempt counts kept per IP address.",
      "Sign-in attempt counts older than a day and ended sessions are deleted every night.",
      "Wording on the home, Product and About pages no longer claims more than Sprintwise can show.",
      "The database connection asks for full certificate checks by name, as it already did in practice.",
    ],
  },
  {
    version: "v2.12",
    date: "2026-10-09",
    title: "Forms keep what you typed",
    summary: "Fixes from testing the unplanned-work features on the live site.",
    items: [
      "If a story can't be saved (say its key is taken), everything you typed stays in the form instead of being cleared.",
      "After saving a sprint snapshot, the stories you ticked stay ticked.",
      "\"Why scope changed\" counts changes as well as points, so a bug added without points still shows.",
      "The planning helper's note on unplanned work reads more clearly, and the chart's Today label no longer runs off the edge.",
    ],
  },
  {
    version: "v2.11",
    date: "2026-10-09",
    title: "Honest about unplanned work",
    summary: "Bugs added mid-sprint are tagged by themselves and counted even without points, and planning explains the room velocity already leaves.",
    items: [
      "Work of type Bug, Defect, Incident or Hotfix added mid-sprint is tagged \"Bug or incident\" by itself. A reason you choose is never replaced.",
      "Scope added says how many new stories have no estimate, so a sprint flooded with unestimated bugs no longer reads as \"0 pts added\".",
      "The planning helper says how much work usually arrives mid-sprint, and that velocity already leaves room for it, so no extra buffer is taken off.",
      "Refinement and the Guide say estimates include testing.",
    ],
  },
  {
    version: "v2.10",
    date: "2026-10-08",
    title: "Faster on phones",
    summary: "A speed and accessibility check of every page, and fixes from it and from testing on a phone.",
    items: [
      "The home page is ready sooner on phones: its headline no longer fades in from invisible, and the video's preview image is half the size.",
      "On a phone, the project tabs all fit on screen and the sprint report's numbers wrap onto two rows.",
      "The demo's own story scores as you type, like the home page.",
      "Backlog search addresses leave out empty filters.",
    ],
  },
  {
    version: "v2.9",
    date: "2026-10-08",
    title: "Polished after a full click-through",
    summary: "Every page tested by hand like a user would. Fixes for what turned up, and the code is now MIT-licensed.",
    items: [
      "The Backlog tab stays lit after an import; before, the Import tab could stay highlighted.",
      "Editing a story no longer marks unchanged acceptance criteria as Changed, and a new story starts as To Do.",
      "The second-look and edited counts follow the band filter, so the number matches what a click shows.",
      "The sprint chart's caption compares scope with the day-one commitment, even when both happen on the same day.",
      "Trends leave out a sprint until it ends, so a running sprint doesn't drag the averages down.",
      "The demo video starts on the product instead of a blank white screen, and tapping a demo story on a phone shows its details.",
      "Product, Guide and About pages describe refinement, shared backlogs and the Jira connection; the code is MIT-licensed.",
    ],
  },
  {
    version: "v2.8",
    date: "2026-10-08",
    title: "Tighter on the details",
    summary: "Deleting your account also cancels GitHub access and signs you out at once, and the code is scanned for security bugs on every change.",
    items: [
      "Deleting your account cancels Sprintwise's access to your GitHub account and signs the browser out straight away.",
      "Deleting a project or your account, and sending to or syncing with Jira, check your sign-in afresh, so signing out elsewhere applies to them at once.",
      "GitHub's code scanning checks every change for security bugs.",
      "New versions of the libraries Sprintwise uses wait a day before they can be installed.",
      "The Privacy page says sessions record the browser type and IP address they started from.",
    ],
  },
  {
    version: "v2.7",
    date: "2026-10-08",
    title: "Security check",
    summary: "A full security review of the site, and fixes for everything it found.",
    items: [
      "Atlassian can only connect Jira to a signed-in account; it can never be used to sign in.",
      "Text written to slow the site down (in a story or a Jira ticket) is now read as fast as any other.",
      "Exported CSV files can't run as spreadsheet formulas, and re-import exactly as before.",
      "Pages may only load content from Sprintwise itself (plus GitHub profile pictures), and stored GitHub or Atlassian keys can't be read from a page.",
      "Sign-in limits repeated tries, and the weekly Atlassian check only runs when Vercel calls it.",
    ],
  },
  {
    version: "v2.6",
    date: "2026-10-08",
    title: "Ready to share the Jira connection",
    summary: "Sprintwise now does the weekly privacy check Atlassian requires before other companies can connect.",
    items: [
      "Once a week, Sprintwise tells Atlassian which Atlassian account IDs it keeps. If Atlassian says an account was closed, its Jira connection is deleted.",
      "Sprintwise keeps only the account ID from your Atlassian account, not your name, email or profile. The Privacy page says so.",
    ],
  },
  {
    version: "v2.5",
    date: "2026-10-07",
    title: "Tidier dropdowns",
    summary: "A story's status is picked from a list, and every dropdown's arrow sits neatly inside its box.",
    items: [
      "In the backlog and sprint tables, a story's status is a dropdown: To Do, In Progress, the statuses your stories already use, then your done statuses. Picking one saves it.",
      "To type a brand-new status, edit the story, or tick stories and use Set status.",
      "Every dropdown has the same arrow, as far from the right edge as the text is from the left, in light and dark themes.",
      "Clicking Ready, Needs work or Not ready, or changing a filter, keeps the page where it is instead of jumping to the top.",
    ],
  },
  {
    version: "v2.4",
    date: "2026-10-07",
    title: "Clicks that always answer",
    summary: "A click made while a page is still getting ready isn't lost, every button shows it's working, and Jira sync is more careful.",
    items: [
      "A page shows a moment before its buttons work. A click in that moment now happens as soon as the page is ready, instead of doing nothing.",
      "Sync from Jira says \"Syncing…\" the moment you click; Set status and Turn off the link also show they're working.",
      "Sync adds only issues created in Jira since the last import or sync, so issues you left out at import stay out.",
      "On Jira sites without an acceptance-criteria field, Send to Jira puts the criteria in the description under an \"Acceptance criteria\" heading.",
    ],
  },
  {
    version: "v2.3",
    date: "2026-10-07",
    title: "Fits newer Jira projects",
    summary: "Acceptance criteria written inside the description count, and Jira's Feature type is scored as a story.",
    items: [
      "Many Jira projects have no acceptance-criteria field, so teams write them in the description. Criteria under an \"Acceptance criteria\" heading there now count (rules v5).",
      "The heading can be a Jira heading, bold text, a Markdown heading or \"Acceptance criteria:\"; the list ends at the next heading.",
      "Story pages, refinement and shared backlogs show those criteria and say where they came from.",
      "Feature, the story type in Jira's newer templates, gets the same story-format checks as Story.",
    ],
  },
  {
    version: "v2.2",
    date: "2026-10-07",
    title: "Connect Jira",
    summary: "Import straight from a Jira search, sync with one click, and send your edits back. No CSV needed.",
    items: [
      "Connect your Atlassian account once from a project's Import page; tokens are stored encrypted.",
      "Pick a Jira site and a search (JQL); the issues open in the same preview as a CSV, to filter and tick.",
      "Sync from Jira re-runs the saved search: it updates stories and adds new ones, and never overwrites a story you edited here.",
      "Send to Jira writes your edits back: title, description, acceptance criteria and points, from a story or the whole backlog.",
      "Disconnect from your Account page at any time.",
    ],
  },
  {
    version: "v2.1",
    date: "2026-10-07",
    title: "Refinement mode",
    summary: "A meeting screen for refinement: one story at a time, what's missing, and the team's estimate in one click.",
    items: [
      "Refinement walks the unfinished stories that aren't Ready yet (or all unfinished ones), in priority order.",
      "Each story shows its text, its score and what to fix, and any second-look hints.",
      "Record the team's agreed size with one click (1, 2, 3, 5, 8, 13) or a number key; the score updates.",
      "Edit story from refinement brings you back to the same story; arrow keys move between stories.",
      "The end shows how many unfinished stories are Ready and how many still need an estimate.",
    ],
  },
  {
    version: "v2.0",
    date: "2026-10-07",
    title: "Share the backlog",
    summary: "A first way to share with the team: a read-only backlog link for refinement, and a home page for the AI era.",
    items: [
      "Share a read-only link to the backlog: the team sees every unfinished story, its score and what to fix, without an account.",
      "Order the shared backlog by priority or weakest first; open a story to see its description, criteria and second-look hints.",
      "Turn the link off at any time; a new link is always different from the old one.",
      "A new home page: AI writes the tickets, Sprintwise checks they're ready.",
    ],
  },
  {
    version: "v1.14",
    date: "2026-10-07",
    title: "Worth a second look",
    summary: "AI writes the ticket; Sprintwise spots the signs nobody read it through.",
    items: [
      "A \"Worth a second look\" list on each story and live while editing: text left over from an AI chat, unfilled placeholders, criteria that would fit any story, filler words, and results promised with a made-up-looking figure.",
      "These hints don't change the score. Chat leftovers and unfilled placeholders do keep a story from being Ready (rules v4).",
      "The backlog marks these stories and can list only them.",
    ],
  },
  {
    version: "v1.13",
    date: "2026-10-07",
    title: "Reads like Jira",
    summary: "Stories from Jira show their formatting, and the edit page keeps both versions lined up.",
    items: [
      "Descriptions and acceptance criteria written with Jira's formatting (headings, bold, code, {noformat} blocks, lists, tables, links) show the way Jira shows them.",
      "When editing, the Before column shows the formatted text, with Show as typed for a character-by-character comparison.",
      "The new version's boxes grow with the text, so both columns stay the same length.",
      "Copy for Jira still copies the original text, so Jira keeps its own formatting.",
      "Column choices no longer remember \"Not in this file\", so a later export with that column is matched again.",
    ],
  },
  {
    version: "v1.12",
    date: "2026-10-07",
    title: "Honest counts, fair scores, back to Jira",
    summary: "Finished work leaves the readiness counts, bugs and tasks aren't asked for user stories, and edits made here find their way back to Jira.",
    items: [
      "Finished stories (your done statuses) are left out of \"X of Y ready\" and hidden from the backlog until you click Show finished. Next to fix skips them.",
      "Stories keep Jira's issue type. Bugs, tasks and other non-stories skip the \"As a … I want … so that …\" checks, with a note saying so; every other check still applies.",
      "Filter the backlog and the import preview by type, and change a story's type when editing it.",
      "Stories edited here are marked \"Edited here\". Copy the description or acceptance criteria for Jira, then mark the story as copied.",
      "Download the edited stories as a CSV with Jira's column names, and a re-import leaves edited stories unticked so Jira's older text doesn't replace your work.",
      "A file picked before the page finished loading is now read too.",
    ],
  },
  {
    version: "v1.11",
    date: "2026-10-07",
    title: "Before and after",
    summary: "Edit a story with its saved version beside every field, and imports that leave out finished work.",
    items: [
      "Editing a story shows what it said before next to each field, marks what you changed, and has Restore to put a field back.",
      "The live score shows the saved score and how far your edits have moved it.",
      "Imports leave finished stories (your project's done statuses) unticked: finished work needs no readiness check.",
      "If an import has no Description or Acceptance criteria column, the preview says so before you import.",
    ],
  },
  {
    version: "v1.10",
    date: "2026-10-07",
    title: "Import any Jira export",
    summary: "Big exports, unfamiliar column names and mixed backlogs import without touching Excel.",
    items: [
      "Files of up to 1,000 stories open in the preview; tick the ones you want and import up to 500 at a time.",
      "Filter the preview by text, status, epic or label, then \"Tick only these\".",
      "Match columns yourself when Sprintwise doesn't recognise a name; the choice is remembered for the project's next import.",
      "Rows with a problem are flagged on their own instead of rejecting the whole file.",
      "Only the ticked stories leave your computer; the rest of the file is read in the browser and never sent.",
      "Stories keep their Jira epic (from the Parent or Epic column), shown in the backlog with an Epic filter.",
      "A Numbers or Excel file saved with a .csv name is recognised, with steps to export a real CSV.",
    ],
  },
  {
    version: "v1.9",
    date: "2026-10-06",
    title: "Quicker on the click",
    summary: "Pages answer the moment you click, the app runs next to its database, and CSV imports are easier to get right.",
    items: [
      "The app now runs in Frankfurt, next to its database, instead of across the Atlantic.",
      "Clicking a project tab lights it up at once and shows a placeholder while the page loads.",
      "Sign-in is checked from a signed cookie for five minutes at a time, saving a database trip on every click.",
      "Drag a CSV onto the file box, or remove a chosen file and pick another.",
      "When an import is missing columns, the error lists the columns the file does have; Jira's \"Work item key\", \"Custom field (…)\" headers and Excel's UTF-16 files now work.",
      "Accessibility: the phone top bar and the shared report's top bar are marked as page headers, and the demo's story buttons are bigger targets.",
    ],
  },
  {
    version: "v1.8",
    date: "2026-10-05",
    title: "Listening",
    summary: "Cookie-free visit counts, and a Send feedback link on every page.",
    items: [
      "Send feedback in the footer and the app sidebar opens a short GitHub form for ideas and problems.",
      "The live site counts page views with Vercel Web Analytics: no cookies, and ids, share tokens and search terms are removed first.",
      "The Privacy page says exactly what is counted.",
    ],
  },
  {
    version: "v1.7",
    date: "2026-10-05",
    title: "See the sprint move",
    summary: "A burn-up chart on the sprint page and report, and trends that start talking from the second sprint.",
    items: [
      "A burn-up chart: scope and work done on each snapshot day, against what was committed on day one.",
      "The chart is on the one-page report too; the report now lists the 10 most recent scope changes.",
      "Trends compare the latest sprint with the one before from the second sprint, and averages from the fourth.",
    ],
  },
  {
    version: "v1.6",
    date: "2026-10-05",
    title: "A backlog you can run",
    summary: "Put the backlog in priority order, find stories fast, change several at once, and move from one weak story to the next.",
    items: [
      "Priority order: drag a story by its handle, or use the arrow keys. The export and the sprint picker follow it.",
      "Search by key or title, and filter by status as well as band.",
      "Tick several stories to set their status or delete them together.",
      "“Next to fix” on a story jumps to the next weakest one that isn't Ready.",
    ],
  },
  {
    version: "v1.5",
    date: "2026-10-05",
    title: "Sprints that keep themselves up to date",
    summary: "Change a status or estimate in a click, and a sprint built from the backlog records it for you.",
    items: [
      "Change status and points straight from the backlog list and the sprint page.",
      "Sprints built from the backlog record each change by themselves: no Save snapshot step.",
      "One automatic snapshot per day; undoing an edit the same day removes it, and reasons you tagged are kept.",
      "Sprints kept with CSVs remind you when the last snapshot is 3 or more days old.",
    ],
  },
  {
    version: "v1.4",
    date: "2026-10-05",
    title: "A score that's harder to fool",
    summary: "Stories with the right shape but vague content no longer pass, and each thing to fix is listed once.",
    items: [
      "“As a user” no longer counts: name who the story is for.",
      "Bigger stories need more acceptance criteria: 2 from 5 points, 3 from 13.",
      "More vague words, such as works, properly, better and stuff, each with a plain alternative.",
      "One reason per missing thing: no criteria shows as one line, not two.",
      "Existing scores update on their own; custom vague-word lists are kept.",
    ],
  },
  {
    version: "v1.3",
    date: "2026-10-05",
    title: "More forgiving",
    summary: "Fewer ways to lose work by accident, and completion that uses your team's own words for done.",
    items: [
      "Undo a baseline locked by mistake, until the first later snapshot is saved.",
      "Leaving a story with unsaved changes asks first.",
      "Choose which statuses count as done, such as Released or Accepted, in project settings.",
      "Delete buttons moved to the foot of the story and sprint pages, away from Edit.",
      "Clearer first steps for new projects, and tidier wording throughout.",
    ],
  },
  {
    version: "v1.2",
    date: "2026-10-03",
    title: "Built for Product Owners",
    summary: "Plan with your team's real velocity, see why scope changed, watch trends, and share reports with stakeholders.",
    items: [
      "Trends: velocity, completion, churn and readiness across sprints, with plain-English insights.",
      "Planning helper: readiness per story, your usual velocity, and a warning before committing unready stories.",
      "Sprint goals, and a reason on every scope change; the report adds them up.",
      "Share a read-only report link with stakeholders, and turn it off any time.",
      "Your team's own readiness checks, writing help without AI, CSV export and copy as text.",
    ],
  },
  {
    version: "v1.1",
    date: "2026-10-03",
    title: "Easier without Jira, and safer",
    summary: "Edit stories with a live score, run a sprint straight from the backlog, and a guide for newcomers.",
    items: [
      "Edit any saved story; the score updates as you type.",
      "Lock a baseline and save snapshots by ticking stories in the backlog. No CSV needed.",
      "New projects get a Getting started checklist, 12 sample stories on request, and a pre-filled two-week sprint.",
      "A Guide page explains every step, number and term.",
      "Security: input limits, security headers, shared sign-in rate limiting and encrypted GitHub tokens.",
    ],
  },
  {
    version: "v1.0",
    date: "2026-10-03",
    title: "Sprintwise version 1",
    summary: "All 18 version 1 stories done: the readiness check, scope tracking and the sprint report, live and tested.",
    items: [
      "Nine fixed rules score every story out of 100, with a reason for every point lost.",
      "Unestimated or oversized stories can't be Ready, whatever their score.",
      "Lock a day-one baseline, upload later snapshots, and see added, removed, churn and completion.",
      "A one-page printable report, including whether the stories that changed scored lower before planning.",
      "GitHub sign-in, a privacy page and full account deletion.",
      "Light, dark and system themes; WCAG 2.1 AA contrast; fully usable by keyboard.",
    ],
  },
  {
    version: "v0.6",
    date: "2026-10-03",
    title: "Rule settings and demo video",
    summary: "Teams can tune the rules per project, and a narrated walkthrough shows the whole product in two minutes.",
    items: [
      "Max story points and the vague-word list per project; saving re-scores every story.",
      "A 2-minute demo video with a natural AI voice-over and captions.",
      "Keyboard pass: the closed mobile menu leaves the Tab order and the theme switch is one Tab stop.",
    ],
  },
  {
    version: "v0.5",
    date: "2026-10-02",
    title: "Redesign, sample sprint and report",
    summary: "A new interface with light and dark themes, and a demo that shows a whole sprint without signing in.",
    items: [
      "A sidebar and project tabs: Backlog, Sprints, Import, Settings.",
      "Light, Dark and System themes, with score rings coloured by band.",
      "The demo gained an invented sample sprint and its one-page report.",
      "GitHub sign-in works on the first click, even before the page's scripts load.",
    ],
  },
  {
    version: "v0.4",
    date: "2026-10-01",
    title: "Live on Vercel",
    summary: "The first public deploy, with scope tracking and the sprint report.",
    items: [
      "Sprints with a locked baseline and dated snapshots, matched by story key.",
      "Net change, churn and completion, with a dated change log.",
      "Production database migrations run only on production deploys.",
    ],
  },
  {
    version: "v0.1",
    date: "2026-10-01",
    title: "Foundations and the readiness check",
    summary: "The rules engine, the backlog and CSV import.",
    items: [
      "The nine readiness rules, each with unit tests.",
      "Paste a story or import a CSV, including a Jira export.",
      "A public demo with an invented backlog that needs no account.",
    ],
  },
];
